/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF,  } from "@react-three/drei";
import { GLTF,  } from "three-stdlib";
import { addGradColor } from "./addGradColor";
import { addSpread } from "./addSpread";
import { addLightLine } from "./addLightLine";
import { addToTopLine } from "./addToTopLine";
import FlyLine from "./FlyLine";
import FlyLineShader from "./FlyLineShader";

type GLTFResult = GLTF & {
  nodes: {
    Layerbuildings: THREE.Mesh;
    Layertopography: THREE.Mesh;
  };
  materials: {};
};

export function City2(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/model/city2.gltf") as GLTFResult;
  nodes.Layerbuildings.material = new THREE.MeshBasicMaterial({
    color: new THREE.Color(0x0c0e33),
  });
  nodes.Layerbuildings.material.onBeforeCompile = function (shader) {
    shader.fragmentShader = shader.fragmentShader.replace(
      "#include <dithering_fragment>",
      `
    #include <dithering_fragment>
    //#end#
    `
    );
    addGradColor(shader, nodes.Layerbuildings);
    addSpread(shader);
    addLightLine(shader);
    addToTopLine(shader);
  };

  return (
    <group {...props} dispose={null}>
      {/* <group name="sun" position={[100, 50, 100]} rotation={[-Math.PI / 2, 0, 0]}>
        <pointLight intensity={10} />
      </group> */}

      <mesh
        geometry={nodes.Layerbuildings.geometry}
        material={nodes.Layerbuildings.material}
      />
      <mesh
        geometry={nodes.Layertopography.geometry}
        material={nodes.Layertopography.material}
      />
      <group name="LayerbuildingsBorderLine">
      <lineSegments material-color="#FF9800">
        <edgesGeometry args={[nodes.Layerbuildings.geometry]}></edgesGeometry>
      </lineSegments>
      </group>
      <group name="FlyLine">
        <FlyLine position={{
          x:200,
          y:50,
          z:-100
        }}
        lineWidth={5}
        />
        <FlyLine position={{
          x:100,
          y:40,
          z:100
        }} 
        duration={1}
        lineWidth={2}
        />
      </group>
      <group name="FlyLineShader">
        <FlyLineShader position={{
            x:300,
            y:100,
            z:200
        }}
        count={4000}
        color="red"
        />
         <FlyLineShader position={{
            x:-300,
            y:100,
            z:-200
        }}
        count={2000}
      
        />
      </group>
    </group>
  );
}

useGLTF.preload("/model/city2.gltf");
